import Description from "../../components/ui/Description";
import Input from "../../components/ui/Input";
import SectionTitle from "../../components/ui/SectionTitle";
import addCarBanner from "./../../assets/addCarBanner.png";
import { Button } from "@material-tailwind/react";
import { useFormik } from "formik";
import * as yup from "yup";
import SelectInput from "../../components/ui/SelectInput";
import { useAddCarMutation } from "../../api/carApi";

function AddCar() {
  const [addCar, { isLoading, isError, message }] = useAddCarMutation();
  const makes = [
    {
      brand: "Seat",
      models: [
        "Alhambra",
        "Altea",
        "Altea XL",
        "Arosa",
        "Cordoba",
        "Cordoba Vario",
        "Exeo",
        "Ibiza",
        "Ibiza ST",
        "Exeo ST",
        "Leon",
        "Leon ST",
        "Inca",
        "Mii",
        "Toledo",
      ],
    },
    {
      brand: "Renault",
      models: [
        "Captur",
        "Clio",
        "Clio Grandtour",
        "Espace",
        "Express",
        "Fluence",
        "Grand Espace",
        "Grand Modus",
        "Grand Scenic",
        "Kadjar",
        "Kangoo",
        "Kangoo Express",
        "Koleos",
        "Laguna",
        "Laguna Grandtour",
        "Latitude",
        "Mascott",
        "Mégane",
        "Mégane CC",
        "Mégane Combi",
        "Mégane Grandtour",
        "Mégane Coupé",
        "Mégane Scénic",
        "Scénic",
        "Talisman",
        "Talisman Grandtour",
        "Thalia",
        "Twingo",
        "Wind",
        "Zoé",
      ],
    },
    {
      brand: "Peugeot",
      models: [
        "1007",
        "107",
        "106",
        "108",
        "2008",
        "205",
        "205 Cabrio",
        "206",
        "206 CC",
        "206 SW",
        "207",
        "207 CC",
        "207 SW",
        "306",
        "307",
        "307 CC",
        "307 SW",
        "308",
        "308 CC",
        "308 SW",
        "309",
        "4007",
        "4008",
        "405",
        "406",
        "407",
        "407 SW",
        "5008",
        "508",
        "508 SW",
        "605",
        "806",
        "607",
        "807",
        "Bipper",
        "RCZ",
      ],
    },
    {
      brand: "Dacia",
      models: [
        "Dokker",
        "Duster",
        "Lodgy",
        "Logan",
        "Logan MCV",
        "Logan Van",
        "Sandero",
        "Solenza",
      ],
    },
    {
      brand: "Citroën",
      models: [
        "Berlingo",
        "C-Crosser",
        "C-Elissée",
        "C-Zero",
        "C1",
        "C2",
        "C3",
        "C3 Picasso",
        "C4",
        "C4 Aircross",
        "C4 Cactus",
        "C4 Coupé",
        "C4 Grand Picasso",
        "C4 Sedan",
        "C5",
        "C5 Break",
        "C5 Tourer",
        "C6",
        "C8",
        "DS3",
        "DS4",
        "DS5",
        "Evasion",
        "Jumper",
        "Jumpy",
        "Saxo",
        "Nemo",
        "Xantia",
        "Xsara",
      ],
    },
    {
      brand: "Opel",
      models: [
        "Agila",
        "Ampera",
        "Antara",
        "Astra",
        "Astra cabrio",
        "Astra caravan",
        "Astra coupé",
        "Calibra",
        "Campo",
        "Cascada",
        "Corsa",
        "Frontera",
        "Insignia",
        "Insignia kombi",
        "Kadett",
        "Meriva",
        "Mokka",
        "Movano",
        "Omega",
        "Signum",
        "Vectra",
        "Vectra Caravan",
        "Vivaro",
        "Vivaro Kombi",
        "Zafira",
      ],
    },
    {
      brand: "Alfa Romeo",
      models: [
        "145",
        "146",
        "147",
        "155",
        "156",
        "156 Sportwagon",
        "159",
        "159 Sportwagon",
        "164",
        "166",
        "4C",
        "Brera",
        "GTV",
        "MiTo",
        "Crosswagon",
        "Spider",
        "GT",
        "Giulietta",
        "Giulia",
      ],
    },
    {
      brand: "Škoda",
      models: [
        "Favorit",
        "Felicia",
        "Citigo",
        "Fabia",
        "Fabia Combi",
        "Fabia Sedan",
        "Felicia Combi",
        "Octavia",
        "Octavia Combi",
        "Roomster",
        "Yeti",
        "Rapid",
        "Rapid Spaceback",
        "Superb",
        "Superb Combi",
      ],
    },
    {
      brand: "Chevrolet",
      models: [
        "Alero",
        "Aveo",
        "Camaro",
        "Captiva",
        "Corvette",
        "Cruze",
        "Cruze SW",
        "Epica",
        "Equinox",
        "Evanda",
        "HHR",
        "Kalos",
        "Lacetti",
        "Lacetti SW",
        "Lumina",
        "Malibu",
        "Matiz",
        "Monte Carlo",
        "Nubira",
        "Orlando",
        "Spark",
        "Suburban",
        "Tacuma",
        "Tahoe",
        "Trax",
      ],
    },
    {
      brand: "Porsche",
      models: [
        "911 Carrera",
        "911 Carrera Cabrio",
        "911 Targa",
        "911 Turbo",
        "924",
        "944",
        "997",
        "Boxster",
        "Cayenne",
        "Cayman",
        "Macan",
        "Panamera",
      ],
    },
    {
      brand: "Honda",
      models: [
        "Accord",
        "Accord Coupé",
        "Accord Tourer",
        "City",
        "Civic",
        "Civic Aerodeck",
        "Civic Coupé",
        "Civic Tourer",
        "Civic Type R",
        "CR-V",
        "CR-X",
        "CR-Z",
        "FR-V",
        "HR-V",
        "Insight",
        "Integra",
        "Jazz",
        "Legend",
        "Prelude",
      ],
    },
    {
      brand: "Subaru",
      models: [
        "BRZ",
        "Forester",
        "Impreza",
        "Impreza Wagon",
        "Justy",
        "Legacy",
        "Legacy Wagon",
        "Legacy Outback",
        "Levorg",
        "Outback",
        "SVX",
        "Tribeca",
        "Tribeca B9",
        "XV",
      ],
    },
    {
      brand: "Mazda",
      models: [
        "121",
        "2",
        "3",
        "323",
        "323 Combi",
        "323 Coupé",
        "323 F",
        "5",
        "6",
        "6 Combi",
        "626",
        "626 Combi",
        "B-Fighter",
        "B2500",
        "BT",
        "CX-3",
        "CX-5",
        "CX-7",
        "CX-9",
        "Demio",
        "MPV",
        "MX-3",
        "MX-5",
        "MX-6",
        "Premacy",
        "RX-7",
        "RX-8",
        "Xedox 6",
      ],
    },
    {
      brand: "Mitsubishi",
      models: [
        "3000 GT",
        "ASX",
        "Carisma",
        "Colt",
        "Colt CC",
        "Eclipse",
        "Fuso canter",
        "Galant",
        "Galant Combi",
        "Grandis",
        "L200",
        "L200 Pick up",
        "L200 Pick up Allrad",
        "L300",
        "Lancer",
        "Lancer Combi",
        "Lancer Evo",
        "Lancer Sportback",
        "Outlander",
        "Pajero",
        "Pajeto Pinin",
        "Pajero Pinin Wagon",
        "Pajero Sport",
        "Pajero Wagon",
        "Space Star",
      ],
    },
    {
      brand: "Lexus",
      models: [
        "CT",
        "GS",
        "GS 300",
        "GX",
        "IS",
        "IS 200",
        "IS 250 C",
        "IS-F",
        "LS",
        "LX",
        "NX",
        "RC F",
        "RX",
        "RX 300",
        "RX 400h",
        "RX 450h",
        "SC 430",
      ],
    },
    {
      brand: "Toyota",
      models: [
        "4-Runner",
        "Auris",
        "Avensis",
        "Avensis Combi",
        "Avensis Van Verso",
        "Aygo",
        "Camry",
        "Carina",
        "Celica",
        "Corolla",
        "Corolla Combi",
        "Corolla sedan",
        "Corolla Verso",
        "FJ Cruiser",
        "GT86",
        "Hiace",
        "Hiace Van",
        "Highlander",
        "Hilux",
        "Land Cruiser",
        "MR2",
        "Paseo",
        "Picnic",
        "Prius",
        "RAV4",
        "Sequoia",
        "Starlet",
        "Supra",
        "Tundra",
        "Urban Cruiser",
        "Verso",
        "Yaris",
        "Yaris Verso",
      ],
    },
    {
      brand: "BMW",
      models: [
        "i3",
        "i8",
        "M3",
        "M4",
        "M5",
        "M6",
        "Rad 1",
        "Rad 1 Cabrio",
        "Rad 1 Coupé",
        "Rad 2",
        "Rad 2 Active Tourer",
        "Rad 2 Coupé",
        "Rad 2 Gran Tourer",
        "Rad 3",
        "Rad 3 Cabrio",
        "Rad 3 Compact",
        "Rad 3 Coupé",
        "Rad 3 GT",
        "Rad 3 Touring",
        "Rad 4",
        "Rad 4 Cabrio",
        "Rad 4 Gran Coupé",
        "Rad 5",
        "Rad 5 GT",
        "Rad 5 Touring",
        "Rad 6",
        "Rad 6 Cabrio",
        "Rad 6 Coupé",
        "Rad 6 Gran Coupé",
        "Rad 7",
        "Rad 8 Coupé",
        "X1",
        "X3",
        "X4",
        "X5",
        "X6",
        "Z3",
        "Z3 Coupé",
        "Z3 Roadster",
        "Z4",
        "Z4 Roadster",
      ],
    },
    {
      brand: "Volkswagen",
      models: [
        "Amarok",
        "Beetle",
        "Bora",
        "Bora Variant",
        "Caddy",
        "Caddy Van",
        "Life",
        "California",
        "Caravelle",
        "CC",
        "Crafter",
        "Crafter Van",
        "Crafter Kombi",
        "CrossTouran",
        "Eos",
        "Fox",
        "Golf",
        "Golf Cabrio",
        "Golf Plus",
        "Golf Sportvan",
        "Golf Variant",
        "Jetta",
        "LT",
        "Lupo",
        "Multivan",
        "New Beetle",
        "New Beetle Cabrio",
        "Passat",
        "Passat Alltrack",
        "Passat CC",
        "Passat Variant",
        "Passat Variant Van",
        "Phaeton",
        "Polo",
        "Polo Van",
        "Polo Variant",
        "Scirocco",
        "Sharan",
        "T4",
        "T4 Caravelle",
        "T4 Multivan",
        "T5",
        "T5 Caravelle",
        "T5 Multivan",
        "T5 Transporter Shuttle",
        "Tiguan",
        "Touareg",
        "Touran",
      ],
    },
    {
      brand: "Suzuki",
      models: [
        "Alto",
        "Baleno",
        "Baleno kombi",
        "Grand Vitara",
        "Grand Vitara XL-7",
        "Ignis",
        "Jimny",
        "Kizashi",
        "Liana",
        "Samurai",
        "Splash",
        "Swift",
        "SX4",
        "SX4 Sedan",
        "Vitara",
        "Wagon R+",
      ],
    },
    {
      brand: "Mercedes-Benz",
      models: [
        "100 D",
        "115",
        "124",
        "126",
        "190",
        "190 D",
        "190 E",
        "200 - 300",
        "200 D",
        "200 E",
        "210 Van",
        "210 kombi",
        "310 Van",
        "310 kombi",
        "230 - 300 CE Coupé",
        "260 - 560 SE",
        "260 - 560 SEL",
        "500 - 600 SEC Coupé",
        "Trieda A",
        "A",
        "A L",
        "AMG GT",
        "Trieda B",
        "Trieda C",
        "C",
        "C Sportcoupé",
        "C T",
        "Citan",
        "CL",
        "CL",
        "CLA",
        "CLC",
        "CLK Cabrio",
        "CLK Coupé",
        "CLS",
        "Trieda E",
        "E",
        "E Cabrio",
        "E Coupé",
        "E T",
        "Trieda G",
        "G Cabrio",
        "GL",
        "GLA",
        "GLC",
        "GLE",
        "GLK",
        "Trieda M",
        "MB 100",
        "Trieda R",
        "Trieda S",
        "S",
        "S Coupé",
        "SL",
        "SLC",
        "SLK",
        "SLR",
        "Sprinter",
      ],
    },
    {
      brand: "Saab",
      models: [
        "9-3",
        "9-3 Cabriolet",
        "9-3 Coupé",
        "9-3 SportCombi",
        "9-5",
        "9-5 SportCombi",
        "900",
        "900 C",
        "900 C Turbo",
        "9000",
      ],
    },
    {
      brand: "Audi",
      models: [
        "100",
        "100 Avant",
        "80",
        "80 Avant",
        "80 Cabrio",
        "90",
        "A1",
        "A2",
        "A3",
        "A3 Cabriolet",
        "A3 Limuzina",
        "A3 Sportback",
        "A4",
        "A4 Allroad",
        "A4 Avant",
        "A4 Cabriolet",
        "A5",
        "A5 Cabriolet",
        "A5 Sportback",
        "A6",
        "A6 Allroad",
        "A6 Avant",
        "A7",
        "A8",
        "A8 Long",
        "Q3",
        "Q5",
        "Q7",
        "R8",
        "RS4 Cabriolet",
        "RS4/RS4 Avant",
        "RS5",
        "RS6 Avant",
        "RS7",
        "S3/S3 Sportback",
        "S4 Cabriolet",
        "S4/S4 Avant",
        "S5/S5 Cabriolet",
        "S6/RS6",
        "S7",
        "S8",
        "SQ5",
        "TT Coupé",
        "TT Roadster",
        "TTS",
      ],
    },
    {
      brand: "Kia",
      models: [
        "Avella",
        "Besta",
        "Carens",
        "Carnival",
        "Cee`d",
        "Cee`d SW",
        "Cerato",
        "K 2500",
        "Magentis",
        "Opirus",
        "Optima",
        "Picanto",
        "Pregio",
        "Pride",
        "Pro Cee`d",
        "Rio",
        "Rio Combi",
        "Rio sedan",
        "Sephia",
        "Shuma",
        "Sorento",
        "Soul",
        "Sportage",
        "Venga",
      ],
    },
    {
      brand: "Land Rover",
      models: [
        "109",
        "Defender",
        "Discovery",
        "Discovery Sport",
        "Freelander",
        "Range Rover",
        "Range Rover Evoque",
        "Range Rover Sport",
      ],
    },
    {
      brand: "Dodge",
      models: [
        "Avenger",
        "Caliber",
        "Challenger",
        "Charger",
        "Grand Caravan",
        "Journey",
        "Magnum",
        "Nitro",
        "RAM",
        "Stealth",
        "Viper",
      ],
    },
    {
      brand: "Chrysler",
      models: [
        "300 C",
        "300 C Touring",
        "300 M",
        "Crossfire",
        "Grand Voyager",
        "LHS",
        "Neon",
        "Pacifica",
        "Plymouth",
        "PT Cruiser",
        "Sebring",
        "Sebring Convertible",
        "Stratus",
        "Stratus Cabrio",
        "Town & Country",
        "Voyager",
      ],
    },
    {
      brand: "Ford",
      models: [
        "Aerostar",
        "B-Max",
        "C-Max",
        "Cortina",
        "Cougar",
        "Edge",
        "Escort",
        "Escort Cabrio",
        "Escort kombi",
        "Explorer",
        "F-150",
        "F-250",
        "Fiesta",
        "Focus",
        "Focus C-Max",
        "Focus CC",
        "Focus kombi",
        "Fusion",
        "Galaxy",
        "Grand C-Max",
        "Ka",
        "Kuga",
        "Maverick",
        "Mondeo",
        "Mondeo Combi",
        "Mustang",
        "Orion",
        "Puma",
        "Ranger",
        "S-Max",
        "Sierra",
        "Street Ka",
        "Tourneo Connect",
        "Tourneo Custom",
        "Transit",
        "Transit",
        "Transit Bus",
        "Transit Connect LWB",
        "Transit Courier",
        "Transit Custom",
        "Transit kombi",
        "Transit Tourneo",
        "Transit Valnik",
        "Transit Van",
        "Transit Van 350",
        "Windstar",
      ],
    },
    { brand: "Hummer", models: ["H2", "H3"] },
    {
      brand: "Hyundai",
      models: [
        "Accent",
        "Atos",
        "Atos Prime",
        "Coupé",
        "Elantra",
        "Galloper",
        "Genesis",
        "Getz",
        "Grandeur",
        "H 350",
        "H1",
        "H1 Bus",
        "H1 Van",
        "H200",
        "i10",
        "i20",
        "i30",
        "i30 CW",
        "i40",
        "i40 CW",
        "ix20",
        "ix35",
        "ix55",
        "Lantra",
        "Matrix",
        "Santa Fe",
        "Sonata",
        "Terracan",
        "Trajet",
        "Tucson",
        "Veloster",
      ],
    },
    { brand: "Infiniti", models: ["EX", "FX", "G", "G Coupé", "M", "Q", "QX"] },
    {
      brand: "Jaguar",
      models: [
        "Daimler",
        "F-Pace",
        "F-Type",
        "S-Type",
        "Sovereign",
        "X-Type",
        "X-type Estate",
        "XE",
        "XF",
        "XJ",
        "XJ12",
        "XJ6",
        "XJ8",
        "XJ8",
        "XJR",
        "XK",
        "XK8 Convertible",
        "XKR",
        "XKR Convertible",
      ],
    },
    {
      brand: "Jeep",
      models: [
        "Cherokee",
        "Commander",
        "Compass",
        "Grand Cherokee",
        "Patriot",
        "Renegade",
        "Wrangler",
      ],
    },
    {
      brand: "Nissan",
      models: [
        "100 NX",
        "200 SX",
        "350 Z",
        "350 Z Roadster",
        "370 Z",
        "Almera",
        "Almera Tino",
        "Cabstar E - T",
        "Cabstar TL2 Valnik",
        "e-NV200",
        "GT-R",
        "Insterstar",
        "Juke",
        "King Cab",
        "Leaf",
        "Maxima",
        "Maxima QX",
        "Micra",
        "Murano",
        "Navara",
        "Note",
        "NP300 Pickup",
        "NV200",
        "NV400",
        "Pathfinder",
        "Patrol",
        "Patrol GR",
        "Pickup",
        "Pixo",
        "Primastar",
        "Primastar Combi",
        "Primera",
        "Primera Combi",
        "Pulsar",
        "Qashqai",
        "Serena",
        "Sunny",
        "Terrano",
        "Tiida",
        "Trade",
        "Vanette Cargo",
        "X-Trail",
      ],
    },
    {
      brand: "Volvo",
      models: [
        "240",
        "340",
        "360",
        "460",
        "850",
        "850 kombi",
        "C30",
        "C70",
        "C70 Cabrio",
        "C70 Coupé",
        "S40",
        "S60",
        "S70",
        "S80",
        "S90",
        "V40",
        "V50",
        "V60",
        "V70",
        "V90",
        "XC60",
        "XC70",
        "XC90",
      ],
    },
    {
      brand: "Daewoo",
      models: [
        "Espero",
        "Kalos",
        "Lacetti",
        "Lanos",
        "Leganza",
        "Lublin",
        "Matiz",
        "Nexia",
        "Nubira",
        "Nubira kombi",
        "Racer",
        "Tacuma",
        "Tico",
      ],
    },
    {
      brand: "Fiat",
      models: [
        "1100",
        "126",
        "500",
        "500L",
        "500X",
        "850",
        "Barchetta",
        "Brava",
        "Cinquecento",
        "Coupé",
        "Croma",
        "Doblo",
        "Doblo Cargo",
        "Doblo Cargo Combi",
        "Ducato",
        "Ducato Van",
        "Ducato Kombi",
        "Ducato Podvozok",
        "Florino",
        "Florino Combi",
        "Freemont",
        "Grande Punto",
        "Idea",
        "Linea",
        "Marea",
        "Marea Weekend",
        "Multipla",
        "Palio Weekend",
        "Panda",
        "Panda Van",
        "Punto",
        "Punto Cabriolet",
        "Punto Evo",
        "Punto Van",
        "Qubo",
        "Scudo",
        "Scudo Van",
        "Scudo Kombi",
        "Sedici",
        "Seicento",
        "Stilo",
        "Stilo Multiwagon",
        "Strada",
        "Talento",
        "Tipo",
        "Ulysse",
        "Uno",
        "X1/9",
      ],
    },
    {
      brand: "MINI",
      models: [
        "Cooper",
        "Cooper Cabrio",
        "Cooper Clubman",
        "Cooper D",
        "Cooper D Clubman",
        "Cooper S",
        "Cooper S Cabrio",
        "Cooper S Clubman",
        "Countryman",
        "Mini One",
        "One D",
      ],
    },
    {
      brand: "Rover",
      models: ["200", "214", "218", "25", "400", "414", "416", "620", "75"],
    },
    {
      brand: "Smart",
      models: [
        "Cabrio",
        "City-Coupé",
        "Compact Pulse",
        "Forfour",
        "Fortwo cabrio",
        "Fortwo coupé",
        "Roadster",
      ],
    },
  ];
  const carModles = {
    Seat: [
      "Alhambra",
      "Altea",
      "Altea XL",
      "Arosa",
      "Cordoba",
      "Cordoba Vario",
      "Exeo",
      "Ibiza",
      "Ibiza ST",
      "Exeo ST",
      "Leon",
      "Leon ST",
      "Inca",
      "Mii",
      "Toledo",
    ],
    Renault: [
      "Captur",
      "Clio",
      "Clio Grandtour",
      "Espace",
      "Express",
      "Fluence",
      "Grand Espace",
      "Grand Modus",
      "Grand Scenic",
      "Kadjar",
      "Kangoo",
      "Kangoo Express",
      "Koleos",
      "Laguna",
      "Laguna Grandtour",
      "Latitude",
      "Mascott",
      "Mégane",
      "Mégane CC",
      "Mégane Combi",
      "Mégane Grandtour",
      "Mégane Coupé",
      "Mégane Scénic",
      "Scénic",
      "Talisman",
      "Talisman Grandtour",
      "Thalia",
      "Twingo",
      "Wind",
      "Zoé",
    ],
    Peugeot: [
      "1007",
      "107",
      "106",
      "108",
      "2008",
      "205",
      "205 Cabrio",
      "206",
      "206 CC",
      "206 SW",
      "207",
      "207 CC",
      "207 SW",
      "306",
      "307",
      "307 CC",
      "307 SW",
      "308",
      "308 CC",
      "308 SW",
      "309",
      "4007",
      "4008",
      "405",
      "406",
      "407",
      "407 SW",
      "5008",
      "508",
      "508 SW",
      "605",
      "806",
      "607",
      "807",
      "Bipper",
      "RCZ",
    ],
    Dacia: [
      "Dokker",
      "Duster",
      "Lodgy",
      "Logan",
      "Logan MCV",
      "Logan Van",
      "Sandero",
      "Solenza",
    ],
    Citroën: [
      "Berlingo",
      "C-Crosser",
      "C-Elissée",
      "C-Zero",
      "C1",
      "C2",
      "C3",
      "C3 Picasso",
      "C4",
      "C4 Aircross",
      "C4 Cactus",
      "C4 Coupé",
      "C4 Grand Picasso",
      "C4 Sedan",
      "C5",
      "C5 Break",
      "C5 Tourer",
      "C6",
      "C8",
      "DS3",
      "DS4",
      "DS5",
      "Evasion",
      "Jumper",
      "Jumpy",
      "Saxo",
      "Nemo",
      "Xantia",
      "Xsara",
    ],
    Opel: [
      "Agila",
      "Ampera",
      "Antara",
      "Astra",
      "Astra cabrio",
      "Astra caravan",
      "Astra coupé",
      "Calibra",
      "Campo",
      "Cascada",
      "Corsa",
      "Frontera",
      "Insignia",
      "Insignia kombi",
      "Kadett",
      "Meriva",
      "Mokka",
      "Movano",
      "Omega",
      "Signum",
      "Vectra",
      "Vectra Caravan",
      "Vivaro",
      "Vivaro Kombi",
      "Zafira",
    ],
    "Alfa Romeo": [
      "145",
      "146",
      "147",
      "155",
      "156",
      "156 Sportwagon",
      "159",
      "159 Sportwagon",
      "164",
      "166",
      "4C",
      "Brera",
      "GTV",
      "MiTo",
      "Crosswagon",
      "Spider",
      "GT",
      "Giulietta",
      "Giulia",
    ],
    Škoda: [
      "Favorit",
      "Felicia",
      "Citigo",
      "Fabia",
      "Fabia Combi",
      "Fabia Sedan",
      "Felicia Combi",
      "Octavia",
      "Octavia Combi",
      "Roomster",
      "Yeti",
      "Rapid",
      "Rapid Spaceback",
      "Superb",
      "Superb Combi",
    ],
    Chevrolet: [
      "Alero",
      "Aveo",
      "Camaro",
      "Captiva",
      "Corvette",
      "Cruze",
      "Cruze SW",
      "Epica",
      "Equinox",
      "Evanda",
      "HHR",
      "Kalos",
      "Lacetti",
      "Lacetti SW",
      "Lumina",
      "Malibu",
      "Matiz",
      "Monte Carlo",
      "Nubira",
      "Orlando",
      "Spark",
      "Suburban",
      "Tacuma",
      "Tahoe",
      "Trax",
    ],
    Porsche: [
      "911 Carrera",
      "911 Carrera Cabrio",
      "911 Targa",
      "911 Turbo",
      "924",
      "944",
      "997",
      "Boxster",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
    ],
    Honda: [
      "Accord",
      "Accord Coupé",
      "Accord Tourer",
      "City",
      "Civic",
      "Civic Aerodeck",
      "Civic Coupé",
      "Civic Tourer",
      "Civic Type R",
      "CR-V",
      "CR-X",
      "CR-Z",
      "FR-V",
      "HR-V",
      "Insight",
      "Integra",
      "Jazz",
      "Legend",
      "Prelude",
    ],
    Subaru: [
      "BRZ",
      "Forester",
      "Impreza",
      "Impreza Wagon",
      "Justy",
      "Legacy",
      "Legacy Wagon",
      "Legacy Outback",
      "Levorg",
      "Outback",
      "SVX",
      "Tribeca",
      "Tribeca B9",
      "XV",
    ],
    Mazda: [
      "121",
      "2",
      "3",
      "323",
      "323 Combi",
      "323 Coupé",
      "323 F",
      "5",
      "6",
      "6 Combi",
      "626",
      "626 Combi",
      "B-Fighter",
      "B2500",
      "BT",
      "CX-3",
      "CX-5",
      "CX-7",
      "CX-9",
      "Demio",
      "MPV",
      "MX-3",
      "MX-5",
      "MX-6",
      "Premacy",
      "RX-7",
      "RX-8",
      "Xedox 6",
    ],
    Mitsubishi: [
      "3000 GT",
      "ASX",
      "Carisma",
      "Colt",
      "Colt CC",
      "Eclipse",
      "Fuso canter",
      "Galant",
      "Galant Combi",
      "Grandis",
      "L200",
      "L200 Pick up",
      "L200 Pick up Allrad",
      "L300",
      "Lancer",
      "Lancer Combi",
      "Lancer Evo",
      "Lancer Sportback",
      "Outlander",
      "Pajero",
      "Pajeto Pinin",
      "Pajero Pinin Wagon",
      "Pajero Sport",
      "Pajero Wagon",
      "Space Star",
    ],
    Lexus: [
      "CT",
      "GS",
      "GS 300",
      "GX",
      "IS",
      "IS 200",
      "IS 250 C",
      "IS-F",
      "LS",
      "LX",
      "NX",
      "RC F",
      "RX",
      "RX 300",
      "RX 400h",
      "RX 450h",
      "SC 430",
    ],
    Toyota: [
      "4-Runner",
      "Auris",
      "Avensis",
      "Avensis Combi",
      "Avensis Van Verso",
      "Aygo",
      "Camry",
      "Carina",
      "Celica",
      "Corolla",
      "Corolla Combi",
      "Corolla sedan",
      "Corolla Verso",
      "FJ Cruiser",
      "GT86",
      "Hiace",
      "Hiace Van",
      "Highlander",
      "Hilux",
      "Land Cruiser",
      "MR2",
      "Paseo",
      "Picnic",
      "Prius",
      "RAV4",
      "Sequoia",
      "Starlet",
      "Supra",
      "Tundra",
      "Urban Cruiser",
      "Verso",
      "Yaris",
      "Yaris Verso",
    ],
    BMW: [
      "i3",
      "i8",
      "M3",
      "M4",
      "M5",
      "M6",
      "Rad 1",
      "Rad 1 Cabrio",
      "Rad 1 Coupé",
      "Rad 2",
      "Rad 2 Active Tourer",
      "Rad 2 Coupé",
      "Rad 2 Gran Tourer",
      "Rad 3",
      "Rad 3 Cabrio",
      "Rad 3 Compact",
      "Rad 3 Coupé",
      "Rad 3 GT",
      "Rad 3 Touring",
      "Rad 4",
      "Rad 4 Cabrio",
      "Rad 4 Gran Coupé",
      "Rad 5",
      "Rad 5 GT",
      "Rad 5 Touring",
      "Rad 6",
      "Rad 6 Cabrio",
      "Rad 6 Coupé",
      "Rad 6 Gran Coupé",
      "Rad 7",
      "Rad 8 Coupé",
      "X1",
      "X3",
      "X4",
      "X5",
      "X6",
      "Z3",
      "Z3 Coupé",
      "Z3 Roadster",
      "Z4",
      "Z4 Roadster",
    ],
    Volkswagen: [
      "Amarok",
      "Beetle",
      "Bora",
      "Bora Variant",
      "Caddy",
      "Caddy Van",
      "Life",
      "California",
      "Caravelle",
      "CC",
      "Crafter",
      "Crafter Van",
      "Crafter Kombi",
      "CrossTouran",
      "Eos",
      "Fox",
      "Golf",
      "Golf Cabrio",
      "Golf Plus",
      "Golf Sportvan",
      "Golf Variant",
      "Jetta",
      "LT",
      "Lupo",
      "Multivan",
      "New Beetle",
      "New Beetle Cabrio",
      "Passat",
      "Passat Alltrack",
      "Passat CC",
      "Passat Variant",
      "Passat Variant Van",
      "Phaeton",
      "Polo",
      "Polo Van",
      "Polo Variant",
      "Scirocco",
      "Sharan",
      "T4",
      "T4 Caravelle",
      "T4 Multivan",
      "T5",
      "T5 Caravelle",
      "T5 Multivan",
      "T5 Transporter Shuttle",
      "Tiguan",
      "Touareg",
      "Touran",
    ],
    Suzuki: [
      "Alto",
      "Baleno",
      "Baleno kombi",
      "Grand Vitara",
      "Grand Vitara XL-7",
      "Ignis",
      "Jimny",
      "Kizashi",
      "Liana",
      "Samurai",
      "Splash",
      "Swift",
      "SX4",
      "SX4 Sedan",
      "Vitara",
      "Wagon R+",
    ],
    "Mercedes-Benz": [
      "100 D",
      "115",
      "124",
      "126",
      "190",
      "190 D",
      "190 E",
      "200 - 300",
      "200 D",
      "200 E",
      "210 Van",
      "210 kombi",
      "310 Van",
      "310 kombi",
      "230 - 300 CE Coupé",
      "260 - 560 SE",
      "260 - 560 SEL",
      "500 - 600 SEC Coupé",
      "Trieda A",
      "A",
      "A L",
      "AMG GT",
      "Trieda B",
      "Trieda C",
      "C",
      "C Sportcoupé",
      "C T",
      "Citan",
      "CL",
      "CL",
      "CLA",
      "CLC",
      "CLK Cabrio",
      "CLK Coupé",
      "CLS",
      "Trieda E",
      "E",
      "E Cabrio",
      "E Coupé",
      "E T",
      "Trieda G",
      "G Cabrio",
      "GL",
      "GLA",
      "GLC",
      "GLE",
      "GLK",
      "Trieda M",
      "MB 100",
      "Trieda R",
      "Trieda S",
      "S",
      "S Coupé",
      "SL",
      "SLC",
      "SLK",
      "SLR",
      "Sprinter",
    ],
    Saab: [
      "9-3",
      "9-3 Cabriolet",
      "9-3 Coupé",
      "9-3 SportCombi",
      "9-5",
      "9-5 SportCombi",
      "900",
      "900 C",
      "900 C Turbo",
      "9000",
    ],
    Audi: [
      "100",
      "100 Avant",
      "80",
      "80 Avant",
      "80 Cabrio",
      "90",
      "A1",
      "A2",
      "A3",
      "A3 Cabriolet",
      "A3 Limuzina",
      "A3 Sportback",
      "A4",
      "A4 Allroad",
      "A4 Avant",
      "A4 Cabriolet",
      "A5",
      "A5 Cabriolet",
      "A5 Sportback",
      "A6",
      "A6 Allroad",
      "A6 Avant",
      "A7",
      "A8",
      "A8 Long",
      "Q3",
      "Q5",
      "Q7",
      "R8",
      "RS4 Cabriolet",
      "RS4/RS4 Avant",
      "RS5",
      "RS6 Avant",
      "RS7",
      "S3/S3 Sportback",
      "S4 Cabriolet",
      "S4/S4 Avant",
      "S5/S5 Cabriolet",
      "S6/RS6",
      "S7",
      "S8",
      "SQ5",
      "TT Coupé",
      "TT Roadster",
      "TTS",
    ],
    Kia: [
      "Avella",
      "Besta",
      "Carens",
      "Carnival",
      "Cee`d",
      "Cee`d SW",
      "Cerato",
      "K 2500",
      "Magentis",
      "Opirus",
      "Optima",
      "Picanto",
      "Pregio",
      "Pride",
      "Pro Cee`d",
      "Rio",
      "Rio Combi",
      "Rio sedan",
      "Sephia",
      "Shuma",
      "Sorento",
      "Soul",
      "Sportage",
      "Venga",
    ],
    "Land Rover": [
      "109",
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
    ],
    Dodge: [
      "Avenger",
      "Caliber",
      "Challenger",
      "Charger",
      "Grand Caravan",
      "Journey",
      "Magnum",
      "Nitro",
      "RAM",
      "Stealth",
      "Viper",
    ],
    Chrysler: [
      "300 C",
      "300 C Touring",
      "300 M",
      "Crossfire",
      "Grand Voyager",
      "LHS",
      "Neon",
      "Pacifica",
      "Plymouth",
      "PT Cruiser",
      "Sebring",
      "Sebring Convertible",
      "Stratus",
      "Stratus Cabrio",
      "Town & Country",
      "Voyager",
    ],
    Ford: [
      "Aerostar",
      "B-Max",
      "C-Max",
      "Cortina",
      "Cougar",
      "Edge",
      "Escort",
      "Escort Cabrio",
      "Escort kombi",
      "Explorer",
      "F-150",
      "F-250",
      "Fiesta",
      "Focus",
      "Focus C-Max",
      "Focus CC",
      "Focus kombi",
      "Fusion",
      "Galaxy",
      "Grand C-Max",
      "Ka",
      "Kuga",
      "Maverick",
      "Mondeo",
      "Mondeo Combi",
      "Mustang",
      "Orion",
      "Puma",
      "Ranger",
      "S-Max",
      "Sierra",
      "Street Ka",
      "Tourneo Connect",
      "Tourneo Custom",
      "Transit",
      "Transit",
      "Transit Bus",
      "Transit Connect LWB",
      "Transit Courier",
      "Transit Custom",
      "Transit kombi",
      "Transit Tourneo",
      "Transit Valnik",
      "Transit Van",
      "Transit Van 350",
      "Windstar",
    ],
    Hummer: ["H2", "H3"],
    Hyundai: [
      "Accent",
      "Atos",
      "Atos Prime",
      "Coupé",
      "Elantra",
      "Galloper",
      "Genesis",
      "Getz",
      "Grandeur",
      "H 350",
      "H1",
      "H1 Bus",
      "H1 Van",
      "H200",
      "i10",
      "i20",
      "i30",
      "i30 CW",
      "i40",
      "i40 CW",
      "ix20",
      "ix35",
      "ix55",
      "Lantra",
      "Matrix",
      "Santa Fe",
      "Sonata",
      "Terracan",
      "Trajet",
      "Tucson",
      "Veloster",
    ],
    Infiniti: ["EX", "FX", "G", "G Coupé", "M", "Q", "QX"],
    Jaguar: [
      "Daimler",
      "F-Pace",
      "F-Type",
      "S-Type",
      "Sovereign",
      "X-Type",
      "X-type Estate",
      "XE",
      "XF",
      "XJ",
      "XJ12",
      "XJ6",
      "XJ8",
      "XJ8",
      "XJR",
      "XK",
      "XK8 Convertible",
      "XKR",
      "XKR Convertible",
    ],
    Jeep: [
      "Cherokee",
      "Commander",
      "Compass",
      "Grand Cherokee",
      "Patriot",
      "Renegade",
      "Wrangler",
    ],
    Nissan: [
      "100 NX",
      "200 SX",
      "350 Z",
      "350 Z Roadster",
      "370 Z",
      "Almera",
      "Almera Tino",
      "Cabstar E - T",
      "Cabstar TL2 Valnik",
      "e-NV200",
      "GT-R",
      "Insterstar",
      "Juke",
      "King Cab",
      "Leaf",
      "Maxima",
      "Maxima QX",
      "Micra",
      "Murano",
      "Navara",
      "Note",
      "NP300 Pickup",
      "NV200",
      "NV400",
      "Pathfinder",
      "Patrol",
      "Patrol GR",
      "Pickup",
      "Pixo",
      "Primastar",
      "Primastar Combi",
      "Primera",
      "Primera Combi",
      "Pulsar",
      "Qashqai",
      "Serena",
      "Sunny",
      "Terrano",
      "Tiida",
      "Trade",
      "Vanette Cargo",
      "X-Trail",
    ],
    Volvo: [
      "240",
      "340",
      "360",
      "460",
      "850",
      "850 kombi",
      "C30",
      "C70",
      "C70 Cabrio",
      "C70 Coupé",
      "S40",
      "S60",
      "S70",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "V90",
      "XC60",
      "XC70",
      "XC90",
    ],

    Daewoo: [
      "Espero",
      "Kalos",
      "Lacetti",
      "Lanos",
      "Leganza",
      "Lublin",
      "Matiz",
      "Nexia",
      "Nubira",
      "Nubira kombi",
      "Racer",
      "Tacuma",
      "Tico",
    ],
    Fiat: [
      "1100",
      "126",
      "500",
      "500L",
      "500X",
      "850",
      "Barchetta",
      "Brava",
      "Cinquecento",
      "Coupé",
      "Croma",
      "Doblo",
      "Doblo Cargo",
      "Doblo Cargo Combi",
      "Ducato",
      "Ducato Van",
      "Ducato Kombi",
      "Ducato Podvozok",
      "Florino",
      "Florino Combi",
      "Freemont",
      "Grande Punto",
      "Idea",
      "Linea",
      "Marea",
      "Marea Weekend",
      "Multipla",
      "Palio Weekend",
      "Panda",
      "Panda Van",
      "Punto",
      "Punto Cabriolet",
      "Punto Evo",
      "Punto Van",
      "Qubo",
      "Scudo",
      "Scudo Van",
      "Scudo Kombi",
      "Sedici",
      "Seicento",
      "Stilo",
      "Stilo Multiwagon",
      "Strada",
      "Talento",
      "Tipo",
      "Ulysse",
      "Uno",
      "X1/9",
    ],
    MINI: [
      "Cooper",
      "Cooper Cabrio",
      "Cooper Clubman",
      "Cooper D",
      "Cooper D Clubman",
      "Cooper S",
      "Cooper S Cabrio",
      "Cooper S Clubman",
      "Countryman",
      "Mini One",
      "One D",
    ],
    Rover: ["200", "214", "218", "25", "400", "414", "416", "620", "75"],
    Smart: [
      "Cabrio",
      "City-Coupé",
      "Compact Pulse",
      "Forfour",
      "Fortwo cabrio",
      "Fortwo coupé",
      "Roadster",
    ],
  };
  const years = Array.from(
    { length: 100 },
    (ele, i) => new Date().getFullYear() - i
  );
  const engineTypes = [
    "Inline 4",
    "Inline 6",
    "V6",
    "V8",
    "V10",
    "V12",
    "W12",
    "W16",
    "Flat 4 (Boxer)",
    "Electric",
    "Hybrid",
    "Turbocharged Inline 4",
    "Turbocharged Inline 6",
    "Turbocharged V6",
    "Turbocharged V8",
    "Supercharged Inline 4",
    "Supercharged V6",
    "Supercharged V8",
    "Supercharged V10",
    "Supercharged V12",
    "Diesel Inline 4",
    "Diesel Inline 6",
    "Diesel V6",
    "Diesel V8",
    "Diesel V12",
    "V5",
    "V8 Turbocharged",
    "V8 Supercharged",
    "V10 Turbocharged",
    "V10 Supercharged",
    "V12 Turbocharged",
    "V12 Supercharged",
    "Inline 3",
    "Inline 5",
    "Inline 2",
    "Flat 3 (Boxer)",
    "Flat 5 (Boxer)",
    "Electric Motor (Single)",
    "Electric Motor (Dual)",
    "Electric Motor (Tri-Motor)",
    "Plug-in Hybrid",
    "Mild Hybrid",
    "Hydrogen Fuel Cell",
    "Compressed Natural Gas (CNG)",
    "E85 Flex-Fuel",
    "Ethanol Engine",
    "Bio-Diesel Engine",
    "Natural Gas Engine",
    "Hybrid Electric Vehicle (HEV)",
    "Plug-in Hybrid Electric Vehicle (PHEV)",
    "Extended Range Electric Vehicle (EREV)",
    "V4",
    "V6 Hybrid",
    "V8 Hybrid",
    "V8 Diesel",
    "V10 Diesel",
    "V12 Diesel",
    "W6",
    "W8",
    "Rotary (Wankel)",
    "Dual-Clutch Engine",
    "Turbo-Diesel",
    "Twin-Turbo Diesel",
    "Quad-Turbo",
    "Single-Turbo Petrol",
    "Twin-Turbo Petrol",
    "Supercharged Petrol",
    "Turbocharged Hybrid",
    "Electric Range Extender",
    "Fuel Cell Electric",
    "Plug-in Hybrid Diesel",
    "Natural Gas Hybrid",
    "LPG (Liquefied Petroleum Gas)",
    "V8 E85",
    "V8 Bio-Diesel",
    "V8 Compressed Natural Gas",
    "V12 Hybrid",
    "V12 Compressed Natural Gas",
    "V12 Bio-Diesel",
    "Flat 6 (Boxer)",
    "Flat 8 (Boxer)",
    "V16",
    "TDI (Turbocharged Direct Injection)",
    "TSI (Turbocharged Stratified Injection)",
    "TFSI (Turbocharged Fuel Stratified Injection)",
    "GDI (Gasoline Direct Injection)",
    "SDI (Suction Diesel Injection)",
    "CDI (Common Rail Diesel Injection)",
  ];
  const carColors = [
    ["Black", "#000000"],
    ["White", "#FFFFFF"],
    ["Silver", "#C0C0C0"],
    ["Gray", "#808080"],
    ["Red", "#FF0000"],
    ["Blue", "#0000FF"],
    ["Green", "#008000"],
    ["Yellow", "#FFFF00"],
    ["Orange", "#FFA500"],
    ["Purple", "#800080"],
    ["Brown", "#A52A2A"],
    ["Beige", "#F5F5DC"],
    ["Gold", "#FFD700"],
    ["Bronze", "#CD7F32"],
    ["Maroon", "#800000"],
    ["Turquoise", "#40E0D0"],
    ["Teal", "#008080"],
    ["Pink", "#FFC0CB"],
    ["Cyan", "#00FFFF"],
    ["Magenta", "#FF00FF"],
    ["Lavender", "#E6E6FA"],
    ["Cream", "#FFFDD0"],
    ["Tan", "#D2B48C"],
    ["Charcoal", "#36454F"],
    ["Navy Blue", "#001F3F"],
    ["Sky Blue", "#87CEEB"],
    ["Royal Blue", "#4169E1"],
    ["Steel Blue", "#4682B4"],
    ["Sapphire Blue", "#0F52BA"],
    ["Aqua", "#00FFFF"],
    ["Olive Green", "#808000"],
    ["Forest Green", "#228B22"],
    ["Lime Green", "#32CD32"],
    ["Mint Green", "#98FF98"],
    ["Army Green", "#4B5320"],
    ["Dark Green", "#006400"],
    ["Copper", "#B87333"],
    ["Rust", "#B7410E"],
    ["Copper Brown", "#6F4F28"],
    ["Rust Red", "#D04E6D"],
    ["Sand", "#C2B280"],
    ["Pearl White", "#F0F0F0"],
    ["Ivory", "#FFFFF0"],
    ["Almond", "#FFEBCD"],
    ["Burgundy", "#800020"],
    ["Wine Red", "#722F37"],
    ["Salmon", "#FA8072"],
    ["Coral", "#FF7F50"],
    ["Rose", "#FF007F"],
    ["Fuchsia", "#FF00FF"],
    ["Berry", "#7D3F77"],
    ["Lilac", "#C8A2C8"],
    ["Plum", "#DDA0DD"],
    ["Slate Gray", "#708090"],
    ["Gunmetal Gray", "#2A3439"],
    ["Graphite Gray", "#4D4D4D"],
    ["Storm Gray", "#4F4F4F"],
    ["Concrete Gray", "#95A5A6"],
    ["Antique White", "#FAEBD7"],
    ["Snow White", "#FFFAFA"],
    ["Glacier Blue", "#A2C2E0"],
    ["Electric Blue", "#7DF9FF"],
    ["Ocean Blue", "#4F42B5"],
    ["Seafoam Green", "#9FE2BF"],
    ["Jade Green", "#00A36C"],
    ["Pistachio Green", "#93C572"],
    ["Moss Green", "#8A9A5B"],
    ["Teal Blue", "#008C95"],
    ["Raspberry", "#E30B5D"],
    ["Electric Green", "#00FF00"],
    ["Neon Green", "#39FF14"],
    ["Day-Glo Yellow", "#F7E7CE"],
    ["Sunset Orange", "#FF5F00"],
    ["Flame Red", "#E25822"],
    ["Bright Red", "#FF4D4D"],
    ["Crimson", "#DC143C"],
    ["Cardinal Red", "#C8102E"],
    ["Fire Engine Red", "#CE2029"],
    ["Cherry Red", "#CF0234"],
    ["Sangria", "#92000A"],
    ["Blood Orange", "#D74315"],
    ["Tangerine", "#F28500"],
    ["Butterscotch", "#F4A300"],
    ["Pine Green", "#01796F"],
    ["Evergreen", "#005D34"],
    ["Spring Green", "#00FF7F"],
    ["Lime Yellow", "#DFFF00"],
    ["Canary Yellow", "#FFFF99"],
    ["Sunflower Yellow", "#FFDA03"],
    ["Goldenrod", "#DAA520"],
    ["Dandelion Yellow", "#F7E300"],
  ];

  const initialValues = {
    make_id: "",
    model: "",
    mileage: "",
    year: "",
    vin: "",
    license_plate: "",
    engine_type: "",
    color_id: "",
  };
  const validationSchema = yup.object().shape({
    make_id: yup.string().required("Make is required"),
    model: yup.string().required("Model is required"),
    mileage: yup
      .number()
      .positive("Mileage must be a positive number")
      .integer("Mileage must be an integer")
      .required("Mileage is required"),
    year: yup.number().required("Year is required"),
    vin: yup
      .string()
      .matches(
        /^[A-HJ-NPR-Z0-9]{17}$/,
        "VIN must be exactly 17 characters and cannot contain I, O, or Q"
      )
      .required("VIN is required"),
    license_plate: yup.string().required("License plate is required"),
    //color_id: yup.string().required("Color is required"),
    engine_type: yup.string().required("Engine type is required"),
  });

  const onSubmit = async (values) => {
    await addCar(values);
  };

  const formik = useFormik({
    initialValues,
    validationSchema,
    onSubmit,
  });

  return (
    <form
      onSubmit={formik.handleSubmit}
      className="pt-10 sm:pt-10 md:pt-16 lg:pt-28
                flex flex-col lg:flex-row 
                h-auto lg:h-screen 
                w-full
            "
    >
      <img
        src={addCarBanner}
        alt=""
        className="lg:w-6/12 w-full h-[70vh] lg:h-full object-cover "
      />
      <div className="lg:w-6/12 w-full flex flex-col items-center justify-center my-5 lg:my-20">
        <div className="w-11/12 mb-10">
          <SectionTitle
            maintext="add&nbsp;"
            spantext={"your car"}
            hideImg={true}
            textClassName={"!text-lg sm:!text-3xl lg:!text-3xl xl:!text-4xl  "}
          />

          <Description
            className={
              "text-wrap text-center !text-sm sm:!text-lg xl:!text-2xl  "
            }
            text="Enter your vehicle details to get started!"
          />
        </div>
        <div className="w-10/12 flex flex-col overflow-y-auto form-scroll bg-scroll">
          <div className="flex gap-2 pr-2">
            <SelectInput
              formik={formik}
              name={"make_id"}
              label={"Make"}
              placeholder={"Select a Make"}
              values={() =>
                makes.map((make) => {
                  return <option key={make.brand}>{make.brand}</option>;
                })
              }
            />
            <SelectInput
              formik={formik}
              name={"model"}
              label={"Model"}
              placeholder={"BenzS-Class"}
              values={() =>
                carModles[formik.values.make_id]?.map((model) => {
                  return <option key={model}>{model}</option>;
                })
              }
            />
          </div>

          <div className="flex gap-2 pr-2">
            <SelectInput
              formik={formik}
              name={"year"}
              label={"Year"}
              placeholder={"2022"}
              values={() =>
                years.map((year) => {
                  return <option key={year}>{year}</option>;
                })
              }
            />

            <Input
              formik={formik}
              name="mileage"
              label="MIleage"
              placeholder="100.000"
            />
          </div>

          <div className="flex gap-2 pr-2">
            <Input
              formik={formik}
              name="vin"
              label="VIN"
              placeholder="1GNEK13Z42R298984"
              required={true}
            />
            <Input
              formik={formik}
              name="license_plate"
              label="License Plate"
              placeholder="ABC-123"
            />
          </div>
          <div className="flex gap-2 pr-2">
            <SelectInput
              formik={formik}
              name={"color_id"}
              label={"Color"}
              placeholder={"Red"}
              values={() =>
                carColors.map((color) => {
                  return (
                    <option
                      style={{
                        backgroundColor: color[1],
                        color: color[0] == "Black" && "white",
                      }}
                      key={color[0]}
                    >
                      {color[0]}
                    </option>
                  );
                })
              }
            />
            <SelectInput
              formik={formik}
              name={"engine_type"}
              label={"Engine Type"}
              placeholder={"V6 Engine"}
              values={() =>
                engineTypes.map((type) => {
                  return <option key={type}>{type}</option>;
                })
              }
            />
          </div>

          <p className="my-5 text-right pr-2">+ Add New Car</p>

          <Button
            type="submit"
            className="w-full normal-case
                        min-h-3 sm:min-h-12 xl:min-h-20
                        text-sm sm:text-2xl xl:text-3xl
                    "
          >
            {isLoading ? "Loading..." : "Submit"}
          </Button>
        </div>
        {isError && <p className="text-red-500 mt-4">{message}</p>}
      </div>
    </form>
  );
}

export default AddCar;
